#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SAMU")]
	public partial class registerclassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertHorraire_de_la_mission(Horraire_de_la_mission instance);
    partial void UpdateHorraire_de_la_mission(Horraire_de_la_mission instance);
    partial void DeleteHorraire_de_la_mission(Horraire_de_la_mission instance);
    partial void InsertLieu_de_patient_table(Lieu_de_patient_table instance);
    partial void UpdateLieu_de_patient_table(Lieu_de_patient_table instance);
    partial void DeleteLieu_de_patient_table(Lieu_de_patient_table instance);
    partial void InsertpatientT(patientT instance);
    partial void UpdatepatientT(patientT instance);
    partial void DeletepatientT(patientT instance);
    partial void InsertAppelant_table(Appelant_table instance);
    partial void UpdateAppelant_table(Appelant_table instance);
    partial void DeleteAppelant_table(Appelant_table instance);
    partial void InsertAppeltable(Appeltable instance);
    partial void UpdateAppeltable(Appeltable instance);
    partial void DeleteAppeltable(Appeltable instance);
    partial void Insertregistertbl(registertbl instance);
    partial void Updateregistertbl(registertbl instance);
    partial void Deleteregistertbl(registertbl instance);
    #endregion
		
		public registerclassDataContext() : 
				base(global::PFE.Properties.Settings.Default.SAMUConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public registerclassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public registerclassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public registerclassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public registerclassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Appel_Utilisateur_table> Appel_Utilisateur_table
		{
			get
			{
				return this.GetTable<Appel_Utilisateur_table>();
			}
		}
		
		public System.Data.Linq.Table<AppelPatientTable> AppelPatientTable
		{
			get
			{
				return this.GetTable<AppelPatientTable>();
			}
		}
		
		public System.Data.Linq.Table<Horraire_de_la_mission> Horraire_de_la_mission
		{
			get
			{
				return this.GetTable<Horraire_de_la_mission>();
			}
		}
		
		public System.Data.Linq.Table<Lieu_de_patient_table> Lieu_de_patient_table
		{
			get
			{
				return this.GetTable<Lieu_de_patient_table>();
			}
		}
		
		public System.Data.Linq.Table<patientT> patientT
		{
			get
			{
				return this.GetTable<patientT>();
			}
		}
		
		public System.Data.Linq.Table<Appelant_table> Appelant_table
		{
			get
			{
				return this.GetTable<Appelant_table>();
			}
		}
		
		public System.Data.Linq.Table<viewch1> viewch1
		{
			get
			{
				return this.GetTable<viewch1>();
			}
		}
		
		public System.Data.Linq.Table<ageparanne> ageparanne
		{
			get
			{
				return this.GetTable<ageparanne>();
			}
		}
		
		public System.Data.Linq.Table<vicparage> vicparage
		{
			get
			{
				return this.GetTable<vicparage>();
			}
		}
		
		public System.Data.Linq.Table<vicparanne> vicparanne
		{
			get
			{
				return this.GetTable<vicparanne>();
			}
		}
		
		public System.Data.Linq.Table<Appeltable> Appeltable
		{
			get
			{
				return this.GetTable<Appeltable>();
			}
		}
		
		public System.Data.Linq.Table<ficheparmotifcreate> ficheparmotifcreate
		{
			get
			{
				return this.GetTable<ficheparmotifcreate>();
			}
		}
		
		public System.Data.Linq.Table<fichesparappel> fichesparappel
		{
			get
			{
				return this.GetTable<fichesparappel>();
			}
		}
		
		public System.Data.Linq.Table<fichesparmedreg> fichesparmedreg
		{
			get
			{
				return this.GetTable<fichesparmedreg>();
			}
		}
		
		public System.Data.Linq.Table<fichesparparam> fichesparparam
		{
			get
			{
				return this.GetTable<fichesparparam>();
			}
		}
		
		public System.Data.Linq.Table<registertbl> registertbl
		{
			get
			{
				return this.GetTable<registertbl>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Appel_Utilisateur_table")]
	public partial class Appel_Utilisateur_table
	{
		
		private string _identifiant;
		
		private System.Nullable<int> _clefiche;
		
		public Appel_Utilisateur_table()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifiant", DbType="NVarChar(50)")]
		public string identifiant
		{
			get
			{
				return this._identifiant;
			}
			set
			{
				if ((this._identifiant != value))
				{
					this._identifiant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clefiche", DbType="Int")]
		public System.Nullable<int> clefiche
		{
			get
			{
				return this._clefiche;
			}
			set
			{
				if ((this._clefiche != value))
				{
					this._clefiche = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AppelPatientTable")]
	public partial class AppelPatientTable
	{
		
		private System.Nullable<int> _cleappel;
		
		private string _clepatient;
		
		public AppelPatientTable()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cleappel", DbType="Int")]
		public System.Nullable<int> cleappel
		{
			get
			{
				return this._cleappel;
			}
			set
			{
				if ((this._cleappel != value))
				{
					this._cleappel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clepatient", DbType="VarChar(20)")]
		public string clepatient
		{
			get
			{
				return this._clepatient;
			}
			set
			{
				if ((this._clepatient != value))
				{
					this._clepatient = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Horraire_de_la_mission")]
	public partial class Horraire_de_la_mission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _code;
		
		private string _Heuredepart;
		
		private string _Heurearriveaulieu;
		
		private string _Heurebilan;
		
		private string _Heuredepartdestination;
		
		private string _Heurearrivedestination;
		
		private string _Heuredepartsec0;
		
		private string _Heuredisp;
		
		private string _Heureretourbase;
		
		private System.Nullable<int> _cleappel;
		
		private EntityRef<Appeltable> _Appeltable;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnHeuredepartChanging(string value);
    partial void OnHeuredepartChanged();
    partial void OnHeurearriveaulieuChanging(string value);
    partial void OnHeurearriveaulieuChanged();
    partial void OnHeurebilanChanging(string value);
    partial void OnHeurebilanChanged();
    partial void OnHeuredepartdestinationChanging(string value);
    partial void OnHeuredepartdestinationChanged();
    partial void OnHeurearrivedestinationChanging(string value);
    partial void OnHeurearrivedestinationChanged();
    partial void OnHeuredepartsec0Changing(string value);
    partial void OnHeuredepartsec0Changed();
    partial void OnHeuredispChanging(string value);
    partial void OnHeuredispChanged();
    partial void OnHeureretourbaseChanging(string value);
    partial void OnHeureretourbaseChanged();
    partial void OncleappelChanging(System.Nullable<int> value);
    partial void OncleappelChanged();
    #endregion
		
		public Horraire_de_la_mission()
		{
			this._Appeltable = default(EntityRef<Appeltable>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heuredepart", DbType="VarChar(30)")]
		public string Heuredepart
		{
			get
			{
				return this._Heuredepart;
			}
			set
			{
				if ((this._Heuredepart != value))
				{
					this.OnHeuredepartChanging(value);
					this.SendPropertyChanging();
					this._Heuredepart = value;
					this.SendPropertyChanged("Heuredepart");
					this.OnHeuredepartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heurearriveaulieu", DbType="VarChar(30)")]
		public string Heurearriveaulieu
		{
			get
			{
				return this._Heurearriveaulieu;
			}
			set
			{
				if ((this._Heurearriveaulieu != value))
				{
					this.OnHeurearriveaulieuChanging(value);
					this.SendPropertyChanging();
					this._Heurearriveaulieu = value;
					this.SendPropertyChanged("Heurearriveaulieu");
					this.OnHeurearriveaulieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heurebilan", DbType="VarChar(30)")]
		public string Heurebilan
		{
			get
			{
				return this._Heurebilan;
			}
			set
			{
				if ((this._Heurebilan != value))
				{
					this.OnHeurebilanChanging(value);
					this.SendPropertyChanging();
					this._Heurebilan = value;
					this.SendPropertyChanged("Heurebilan");
					this.OnHeurebilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heuredepartdestination", DbType="VarChar(30)")]
		public string Heuredepartdestination
		{
			get
			{
				return this._Heuredepartdestination;
			}
			set
			{
				if ((this._Heuredepartdestination != value))
				{
					this.OnHeuredepartdestinationChanging(value);
					this.SendPropertyChanging();
					this._Heuredepartdestination = value;
					this.SendPropertyChanged("Heuredepartdestination");
					this.OnHeuredepartdestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heurearrivedestination", DbType="VarChar(30)")]
		public string Heurearrivedestination
		{
			get
			{
				return this._Heurearrivedestination;
			}
			set
			{
				if ((this._Heurearrivedestination != value))
				{
					this.OnHeurearrivedestinationChanging(value);
					this.SendPropertyChanging();
					this._Heurearrivedestination = value;
					this.SendPropertyChanged("Heurearrivedestination");
					this.OnHeurearrivedestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heuredepartsec0", DbType="VarChar(30)")]
		public string Heuredepartsec0
		{
			get
			{
				return this._Heuredepartsec0;
			}
			set
			{
				if ((this._Heuredepartsec0 != value))
				{
					this.OnHeuredepartsec0Changing(value);
					this.SendPropertyChanging();
					this._Heuredepartsec0 = value;
					this.SendPropertyChanged("Heuredepartsec0");
					this.OnHeuredepartsec0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heuredisp", DbType="VarChar(30)")]
		public string Heuredisp
		{
			get
			{
				return this._Heuredisp;
			}
			set
			{
				if ((this._Heuredisp != value))
				{
					this.OnHeuredispChanging(value);
					this.SendPropertyChanging();
					this._Heuredisp = value;
					this.SendPropertyChanged("Heuredisp");
					this.OnHeuredispChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heureretourbase", DbType="VarChar(30)")]
		public string Heureretourbase
		{
			get
			{
				return this._Heureretourbase;
			}
			set
			{
				if ((this._Heureretourbase != value))
				{
					this.OnHeureretourbaseChanging(value);
					this.SendPropertyChanging();
					this._Heureretourbase = value;
					this.SendPropertyChanged("Heureretourbase");
					this.OnHeureretourbaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cleappel", DbType="Int")]
		public System.Nullable<int> cleappel
		{
			get
			{
				return this._cleappel;
			}
			set
			{
				if ((this._cleappel != value))
				{
					if (this._Appeltable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncleappelChanging(value);
					this.SendPropertyChanging();
					this._cleappel = value;
					this.SendPropertyChanged("cleappel");
					this.OncleappelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Appeltable_Horraire_de_la_mission", Storage="_Appeltable", ThisKey="cleappel", OtherKey="CleAppel", IsForeignKey=true)]
		public Appeltable Appeltable
		{
			get
			{
				return this._Appeltable.Entity;
			}
			set
			{
				Appeltable previousValue = this._Appeltable.Entity;
				if (((previousValue != value) 
							|| (this._Appeltable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Appeltable.Entity = null;
						previousValue.Horraire_de_la_mission.Remove(this);
					}
					this._Appeltable.Entity = value;
					if ((value != null))
					{
						value.Horraire_de_la_mission.Add(this);
						this._cleappel = value.CleAppel;
					}
					else
					{
						this._cleappel = default(Nullable<int>);
					}
					this.SendPropertyChanged("Appeltable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lieu_de_patient_table")]
	public partial class Lieu_de_patient_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Lieudepatient;
		
		private string _Autrelieu;
		
		private string _Hopital;
		
		private string _service;
		
		private string _IDpatient;
		
		private string _code;
		
		private EntityRef<patientT> _patientT;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLieudepatientChanging(string value);
    partial void OnLieudepatientChanged();
    partial void OnAutrelieuChanging(string value);
    partial void OnAutrelieuChanged();
    partial void OnHopitalChanging(string value);
    partial void OnHopitalChanged();
    partial void OnserviceChanging(string value);
    partial void OnserviceChanged();
    partial void OnIDpatientChanging(string value);
    partial void OnIDpatientChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    #endregion
		
		public Lieu_de_patient_table()
		{
			this._patientT = default(EntityRef<patientT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lieudepatient", DbType="VarChar(20)")]
		public string Lieudepatient
		{
			get
			{
				return this._Lieudepatient;
			}
			set
			{
				if ((this._Lieudepatient != value))
				{
					this.OnLieudepatientChanging(value);
					this.SendPropertyChanging();
					this._Lieudepatient = value;
					this.SendPropertyChanged("Lieudepatient");
					this.OnLieudepatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autrelieu", DbType="VarChar(20)")]
		public string Autrelieu
		{
			get
			{
				return this._Autrelieu;
			}
			set
			{
				if ((this._Autrelieu != value))
				{
					this.OnAutrelieuChanging(value);
					this.SendPropertyChanging();
					this._Autrelieu = value;
					this.SendPropertyChanged("Autrelieu");
					this.OnAutrelieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hopital", DbType="VarChar(20)")]
		public string Hopital
		{
			get
			{
				return this._Hopital;
			}
			set
			{
				if ((this._Hopital != value))
				{
					this.OnHopitalChanging(value);
					this.SendPropertyChanging();
					this._Hopital = value;
					this.SendPropertyChanged("Hopital");
					this.OnHopitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service", DbType="VarChar(20)")]
		public string service
		{
			get
			{
				return this._service;
			}
			set
			{
				if ((this._service != value))
				{
					this.OnserviceChanging(value);
					this.SendPropertyChanging();
					this._service = value;
					this.SendPropertyChanged("service");
					this.OnserviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDpatient", DbType="VarChar(20)")]
		public string IDpatient
		{
			get
			{
				return this._IDpatient;
			}
			set
			{
				if ((this._IDpatient != value))
				{
					if (this._patientT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDpatientChanging(value);
					this.SendPropertyChanging();
					this._IDpatient = value;
					this.SendPropertyChanged("IDpatient");
					this.OnIDpatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="patientT_Lieu_de_patient_table", Storage="_patientT", ThisKey="IDpatient", OtherKey="IDpatient", IsForeignKey=true)]
		public patientT patientT
		{
			get
			{
				return this._patientT.Entity;
			}
			set
			{
				patientT previousValue = this._patientT.Entity;
				if (((previousValue != value) 
							|| (this._patientT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._patientT.Entity = null;
						previousValue.Lieu_de_patient_table.Remove(this);
					}
					this._patientT.Entity = value;
					if ((value != null))
					{
						value.Lieu_de_patient_table.Add(this);
						this._IDpatient = value.IDpatient;
					}
					else
					{
						this._IDpatient = default(string);
					}
					this.SendPropertyChanged("patientT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.patientT")]
	public partial class patientT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDpatient;
		
		private string _Nompatient;
		
		private string _Prenompatient;
		
		private System.Nullable<int> _Agepatient;
		
		private string _Genrepatient;
		
		private string _Gouvernoratpatient;
		
		private string _Gcs;
		
		private string _TA;
		
		private string _Pouls;
		
		private string _FR;
		
		private string _SPO2;
		
		private string _T;
		
		private string _Dextro;
		
		private EntitySet<Lieu_de_patient_table> _Lieu_de_patient_table;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDpatientChanging(string value);
    partial void OnIDpatientChanged();
    partial void OnNompatientChanging(string value);
    partial void OnNompatientChanged();
    partial void OnPrenompatientChanging(string value);
    partial void OnPrenompatientChanged();
    partial void OnAgepatientChanging(System.Nullable<int> value);
    partial void OnAgepatientChanged();
    partial void OnGenrepatientChanging(string value);
    partial void OnGenrepatientChanged();
    partial void OnGouvernoratpatientChanging(string value);
    partial void OnGouvernoratpatientChanged();
    partial void OnGcsChanging(string value);
    partial void OnGcsChanged();
    partial void OnTAChanging(string value);
    partial void OnTAChanged();
    partial void OnPoulsChanging(string value);
    partial void OnPoulsChanged();
    partial void OnFRChanging(string value);
    partial void OnFRChanged();
    partial void OnSPO2Changing(string value);
    partial void OnSPO2Changed();
    partial void OnTChanging(string value);
    partial void OnTChanged();
    partial void OnDextroChanging(string value);
    partial void OnDextroChanged();
    #endregion
		
		public patientT()
		{
			this._Lieu_de_patient_table = new EntitySet<Lieu_de_patient_table>(new Action<Lieu_de_patient_table>(this.attach_Lieu_de_patient_table), new Action<Lieu_de_patient_table>(this.detach_Lieu_de_patient_table));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDpatient", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDpatient
		{
			get
			{
				return this._IDpatient;
			}
			set
			{
				if ((this._IDpatient != value))
				{
					this.OnIDpatientChanging(value);
					this.SendPropertyChanging();
					this._IDpatient = value;
					this.SendPropertyChanged("IDpatient");
					this.OnIDpatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nompatient", DbType="VarChar(20)")]
		public string Nompatient
		{
			get
			{
				return this._Nompatient;
			}
			set
			{
				if ((this._Nompatient != value))
				{
					this.OnNompatientChanging(value);
					this.SendPropertyChanging();
					this._Nompatient = value;
					this.SendPropertyChanged("Nompatient");
					this.OnNompatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenompatient", DbType="VarChar(20)")]
		public string Prenompatient
		{
			get
			{
				return this._Prenompatient;
			}
			set
			{
				if ((this._Prenompatient != value))
				{
					this.OnPrenompatientChanging(value);
					this.SendPropertyChanging();
					this._Prenompatient = value;
					this.SendPropertyChanged("Prenompatient");
					this.OnPrenompatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agepatient", DbType="Int")]
		public System.Nullable<int> Agepatient
		{
			get
			{
				return this._Agepatient;
			}
			set
			{
				if ((this._Agepatient != value))
				{
					this.OnAgepatientChanging(value);
					this.SendPropertyChanging();
					this._Agepatient = value;
					this.SendPropertyChanged("Agepatient");
					this.OnAgepatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genrepatient", DbType="VarChar(20)")]
		public string Genrepatient
		{
			get
			{
				return this._Genrepatient;
			}
			set
			{
				if ((this._Genrepatient != value))
				{
					this.OnGenrepatientChanging(value);
					this.SendPropertyChanging();
					this._Genrepatient = value;
					this.SendPropertyChanged("Genrepatient");
					this.OnGenrepatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gouvernoratpatient", DbType="VarChar(20)")]
		public string Gouvernoratpatient
		{
			get
			{
				return this._Gouvernoratpatient;
			}
			set
			{
				if ((this._Gouvernoratpatient != value))
				{
					this.OnGouvernoratpatientChanging(value);
					this.SendPropertyChanging();
					this._Gouvernoratpatient = value;
					this.SendPropertyChanged("Gouvernoratpatient");
					this.OnGouvernoratpatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gcs", DbType="VarChar(20)")]
		public string Gcs
		{
			get
			{
				return this._Gcs;
			}
			set
			{
				if ((this._Gcs != value))
				{
					this.OnGcsChanging(value);
					this.SendPropertyChanging();
					this._Gcs = value;
					this.SendPropertyChanged("Gcs");
					this.OnGcsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TA", DbType="VarChar(20)")]
		public string TA
		{
			get
			{
				return this._TA;
			}
			set
			{
				if ((this._TA != value))
				{
					this.OnTAChanging(value);
					this.SendPropertyChanging();
					this._TA = value;
					this.SendPropertyChanged("TA");
					this.OnTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pouls", DbType="VarChar(20)")]
		public string Pouls
		{
			get
			{
				return this._Pouls;
			}
			set
			{
				if ((this._Pouls != value))
				{
					this.OnPoulsChanging(value);
					this.SendPropertyChanging();
					this._Pouls = value;
					this.SendPropertyChanged("Pouls");
					this.OnPoulsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FR", DbType="VarChar(20)")]
		public string FR
		{
			get
			{
				return this._FR;
			}
			set
			{
				if ((this._FR != value))
				{
					this.OnFRChanging(value);
					this.SendPropertyChanging();
					this._FR = value;
					this.SendPropertyChanged("FR");
					this.OnFRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPO2", DbType="VarChar(20)")]
		public string SPO2
		{
			get
			{
				return this._SPO2;
			}
			set
			{
				if ((this._SPO2 != value))
				{
					this.OnSPO2Changing(value);
					this.SendPropertyChanging();
					this._SPO2 = value;
					this.SendPropertyChanged("SPO2");
					this.OnSPO2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T", DbType="VarChar(20)")]
		public string T
		{
			get
			{
				return this._T;
			}
			set
			{
				if ((this._T != value))
				{
					this.OnTChanging(value);
					this.SendPropertyChanging();
					this._T = value;
					this.SendPropertyChanged("T");
					this.OnTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dextro", DbType="VarChar(20)")]
		public string Dextro
		{
			get
			{
				return this._Dextro;
			}
			set
			{
				if ((this._Dextro != value))
				{
					this.OnDextroChanging(value);
					this.SendPropertyChanging();
					this._Dextro = value;
					this.SendPropertyChanged("Dextro");
					this.OnDextroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="patientT_Lieu_de_patient_table", Storage="_Lieu_de_patient_table", ThisKey="IDpatient", OtherKey="IDpatient")]
		public EntitySet<Lieu_de_patient_table> Lieu_de_patient_table
		{
			get
			{
				return this._Lieu_de_patient_table;
			}
			set
			{
				this._Lieu_de_patient_table.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lieu_de_patient_table(Lieu_de_patient_table entity)
		{
			this.SendPropertyChanging();
			entity.patientT = this;
		}
		
		private void detach_Lieu_de_patient_table(Lieu_de_patient_table entity)
		{
			this.SendPropertyChanging();
			entity.patientT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Appelant_table")]
	public partial class Appelant_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_appelant;
		
		private string _Nom_appelant;
		
		private string _Telephone_appelant;
		
		private System.Nullable<int> _CIN_appelant;
		
		private System.Nullable<int> _cleappel;
		
		private string _appelant;
		
		private EntitySet<Appeltable> _Appeltable1;
		
		private EntityRef<Appeltable> _Appeltable;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_appelantChanging(int value);
    partial void OnID_appelantChanged();
    partial void OnNom_appelantChanging(string value);
    partial void OnNom_appelantChanged();
    partial void OnTelephone_appelantChanging(string value);
    partial void OnTelephone_appelantChanged();
    partial void OnCIN_appelantChanging(System.Nullable<int> value);
    partial void OnCIN_appelantChanged();
    partial void OncleappelChanging(System.Nullable<int> value);
    partial void OncleappelChanged();
    partial void OnappelantChanging(string value);
    partial void OnappelantChanged();
    #endregion
		
		public Appelant_table()
		{
			this._Appeltable1 = new EntitySet<Appeltable>(new Action<Appeltable>(this.attach_Appeltable1), new Action<Appeltable>(this.detach_Appeltable1));
			this._Appeltable = default(EntityRef<Appeltable>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_appelant", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_appelant
		{
			get
			{
				return this._ID_appelant;
			}
			set
			{
				if ((this._ID_appelant != value))
				{
					this.OnID_appelantChanging(value);
					this.SendPropertyChanging();
					this._ID_appelant = value;
					this.SendPropertyChanged("ID_appelant");
					this.OnID_appelantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_appelant", DbType="NChar(10)")]
		public string Nom_appelant
		{
			get
			{
				return this._Nom_appelant;
			}
			set
			{
				if ((this._Nom_appelant != value))
				{
					this.OnNom_appelantChanging(value);
					this.SendPropertyChanging();
					this._Nom_appelant = value;
					this.SendPropertyChanged("Nom_appelant");
					this.OnNom_appelantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone_appelant", DbType="NChar(10)")]
		public string Telephone_appelant
		{
			get
			{
				return this._Telephone_appelant;
			}
			set
			{
				if ((this._Telephone_appelant != value))
				{
					this.OnTelephone_appelantChanging(value);
					this.SendPropertyChanging();
					this._Telephone_appelant = value;
					this.SendPropertyChanged("Telephone_appelant");
					this.OnTelephone_appelantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIN_appelant", DbType="Int")]
		public System.Nullable<int> CIN_appelant
		{
			get
			{
				return this._CIN_appelant;
			}
			set
			{
				if ((this._CIN_appelant != value))
				{
					this.OnCIN_appelantChanging(value);
					this.SendPropertyChanging();
					this._CIN_appelant = value;
					this.SendPropertyChanged("CIN_appelant");
					this.OnCIN_appelantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cleappel", DbType="Int")]
		public System.Nullable<int> cleappel
		{
			get
			{
				return this._cleappel;
			}
			set
			{
				if ((this._cleappel != value))
				{
					if (this._Appeltable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncleappelChanging(value);
					this.SendPropertyChanging();
					this._cleappel = value;
					this.SendPropertyChanged("cleappel");
					this.OncleappelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appelant", DbType="VarChar(30)")]
		public string appelant
		{
			get
			{
				return this._appelant;
			}
			set
			{
				if ((this._appelant != value))
				{
					this.OnappelantChanging(value);
					this.SendPropertyChanging();
					this._appelant = value;
					this.SendPropertyChanged("appelant");
					this.OnappelantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Appelant_table_Appeltable", Storage="_Appeltable1", ThisKey="ID_appelant", OtherKey="Idappelant")]
		public EntitySet<Appeltable> Appeltable1
		{
			get
			{
				return this._Appeltable1;
			}
			set
			{
				this._Appeltable1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Appeltable_Appelant_table", Storage="_Appeltable", ThisKey="cleappel", OtherKey="CleAppel", IsForeignKey=true)]
		public Appeltable Appeltable
		{
			get
			{
				return this._Appeltable.Entity;
			}
			set
			{
				Appeltable previousValue = this._Appeltable.Entity;
				if (((previousValue != value) 
							|| (this._Appeltable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Appeltable.Entity = null;
						previousValue.Appelant_table.Remove(this);
					}
					this._Appeltable.Entity = value;
					if ((value != null))
					{
						value.Appelant_table.Add(this);
						this._cleappel = value.CleAppel;
					}
					else
					{
						this._cleappel = default(Nullable<int>);
					}
					this.SendPropertyChanged("Appeltable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Appeltable1(Appeltable entity)
		{
			this.SendPropertyChanging();
			entity.Appelant_table1 = this;
		}
		
		private void detach_Appeltable1(Appeltable entity)
		{
			this.SendPropertyChanging();
			entity.Appelant_table1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewch1")]
	public partial class viewch1
	{
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _numfiches;
		
		public viewch1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this._year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numfiches", DbType="Int")]
		public System.Nullable<int> numfiches
		{
			get
			{
				return this._numfiches;
			}
			set
			{
				if ((this._numfiches != value))
				{
					this._numfiches = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ageparanne")]
	public partial class ageparanne
	{
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _year;
		
		public ageparanne()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this._year = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vicparage")]
	public partial class vicparage
	{
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _nbvic;
		
		public vicparage()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbvic", DbType="Int")]
		public System.Nullable<int> nbvic
		{
			get
			{
				return this._nbvic;
			}
			set
			{
				if ((this._nbvic != value))
				{
					this._nbvic = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vicparanne")]
	public partial class vicparanne
	{
		
		private System.Nullable<int> _age;
		
		private System.Nullable<int> _nbvic;
		
		public vicparanne()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbvic", DbType="Int")]
		public System.Nullable<int> nbvic
		{
			get
			{
				return this._nbvic;
			}
			set
			{
				if ((this._nbvic != value))
				{
					this._nbvic = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Appeltable")]
	public partial class Appeltable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CleAppel;
		
		private string _Medecinregulateur;
		
		private System.Nullable<int> _NBvictimes;
		
		private string _Param;
		
		private string _Objetdedemande;
		
		private string _Decisionderegulation;
		
		private string _Vehiculeengage;
		
		private string _Motifdappel;
		
		private string _Typologiepathologie;
		
		private string _pathologie;
		
		private string _Validationmission;
		
		private string _Utilitedemission;
		
		private System.Nullable<int> _Idappelant;
		
		private string _arriveappel;
		
		private string _destinationdesire;
		
		private string _date;
		
		private EntitySet<Horraire_de_la_mission> _Horraire_de_la_mission;
		
		private EntitySet<Appelant_table> _Appelant_table;
		
		private EntityRef<Appelant_table> _Appelant_table1;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCleAppelChanging(int value);
    partial void OnCleAppelChanged();
    partial void OnMedecinregulateurChanging(string value);
    partial void OnMedecinregulateurChanged();
    partial void OnNBvictimesChanging(System.Nullable<int> value);
    partial void OnNBvictimesChanged();
    partial void OnParamChanging(string value);
    partial void OnParamChanged();
    partial void OnObjetdedemandeChanging(string value);
    partial void OnObjetdedemandeChanged();
    partial void OnDecisionderegulationChanging(string value);
    partial void OnDecisionderegulationChanged();
    partial void OnVehiculeengageChanging(string value);
    partial void OnVehiculeengageChanged();
    partial void OnMotifdappelChanging(string value);
    partial void OnMotifdappelChanged();
    partial void OnTypologiepathologieChanging(string value);
    partial void OnTypologiepathologieChanged();
    partial void OnpathologieChanging(string value);
    partial void OnpathologieChanged();
    partial void OnValidationmissionChanging(string value);
    partial void OnValidationmissionChanged();
    partial void OnUtilitedemissionChanging(string value);
    partial void OnUtilitedemissionChanged();
    partial void OnIdappelantChanging(System.Nullable<int> value);
    partial void OnIdappelantChanged();
    partial void OnarriveappelChanging(string value);
    partial void OnarriveappelChanged();
    partial void OndestinationdesireChanging(string value);
    partial void OndestinationdesireChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    #endregion
		
		public Appeltable()
		{
			this._Horraire_de_la_mission = new EntitySet<Horraire_de_la_mission>(new Action<Horraire_de_la_mission>(this.attach_Horraire_de_la_mission), new Action<Horraire_de_la_mission>(this.detach_Horraire_de_la_mission));
			this._Appelant_table = new EntitySet<Appelant_table>(new Action<Appelant_table>(this.attach_Appelant_table), new Action<Appelant_table>(this.detach_Appelant_table));
			this._Appelant_table1 = default(EntityRef<Appelant_table>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CleAppel", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CleAppel
		{
			get
			{
				return this._CleAppel;
			}
			set
			{
				if ((this._CleAppel != value))
				{
					this.OnCleAppelChanging(value);
					this.SendPropertyChanging();
					this._CleAppel = value;
					this.SendPropertyChanged("CleAppel");
					this.OnCleAppelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medecinregulateur", DbType="VarChar(20)")]
		public string Medecinregulateur
		{
			get
			{
				return this._Medecinregulateur;
			}
			set
			{
				if ((this._Medecinregulateur != value))
				{
					this.OnMedecinregulateurChanging(value);
					this.SendPropertyChanging();
					this._Medecinregulateur = value;
					this.SendPropertyChanged("Medecinregulateur");
					this.OnMedecinregulateurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NBvictimes", DbType="Int")]
		public System.Nullable<int> NBvictimes
		{
			get
			{
				return this._NBvictimes;
			}
			set
			{
				if ((this._NBvictimes != value))
				{
					this.OnNBvictimesChanging(value);
					this.SendPropertyChanging();
					this._NBvictimes = value;
					this.SendPropertyChanged("NBvictimes");
					this.OnNBvictimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Param", DbType="VarChar(20)")]
		public string Param
		{
			get
			{
				return this._Param;
			}
			set
			{
				if ((this._Param != value))
				{
					this.OnParamChanging(value);
					this.SendPropertyChanging();
					this._Param = value;
					this.SendPropertyChanged("Param");
					this.OnParamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objetdedemande", DbType="NVarChar(255)")]
		public string Objetdedemande
		{
			get
			{
				return this._Objetdedemande;
			}
			set
			{
				if ((this._Objetdedemande != value))
				{
					this.OnObjetdedemandeChanging(value);
					this.SendPropertyChanging();
					this._Objetdedemande = value;
					this.SendPropertyChanged("Objetdedemande");
					this.OnObjetdedemandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decisionderegulation", DbType="VarChar(30)")]
		public string Decisionderegulation
		{
			get
			{
				return this._Decisionderegulation;
			}
			set
			{
				if ((this._Decisionderegulation != value))
				{
					this.OnDecisionderegulationChanging(value);
					this.SendPropertyChanging();
					this._Decisionderegulation = value;
					this.SendPropertyChanged("Decisionderegulation");
					this.OnDecisionderegulationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vehiculeengage", DbType="VarChar(20)")]
		public string Vehiculeengage
		{
			get
			{
				return this._Vehiculeengage;
			}
			set
			{
				if ((this._Vehiculeengage != value))
				{
					this.OnVehiculeengageChanging(value);
					this.SendPropertyChanging();
					this._Vehiculeengage = value;
					this.SendPropertyChanged("Vehiculeengage");
					this.OnVehiculeengageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motifdappel", DbType="VarChar(20)")]
		public string Motifdappel
		{
			get
			{
				return this._Motifdappel;
			}
			set
			{
				if ((this._Motifdappel != value))
				{
					this.OnMotifdappelChanging(value);
					this.SendPropertyChanging();
					this._Motifdappel = value;
					this.SendPropertyChanged("Motifdappel");
					this.OnMotifdappelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Typologiepathologie", DbType="VarChar(30)")]
		public string Typologiepathologie
		{
			get
			{
				return this._Typologiepathologie;
			}
			set
			{
				if ((this._Typologiepathologie != value))
				{
					this.OnTypologiepathologieChanging(value);
					this.SendPropertyChanging();
					this._Typologiepathologie = value;
					this.SendPropertyChanged("Typologiepathologie");
					this.OnTypologiepathologieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathologie", DbType="VarChar(31)")]
		public string pathologie
		{
			get
			{
				return this._pathologie;
			}
			set
			{
				if ((this._pathologie != value))
				{
					this.OnpathologieChanging(value);
					this.SendPropertyChanging();
					this._pathologie = value;
					this.SendPropertyChanged("pathologie");
					this.OnpathologieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validationmission", DbType="VarChar(20)")]
		public string Validationmission
		{
			get
			{
				return this._Validationmission;
			}
			set
			{
				if ((this._Validationmission != value))
				{
					this.OnValidationmissionChanging(value);
					this.SendPropertyChanging();
					this._Validationmission = value;
					this.SendPropertyChanged("Validationmission");
					this.OnValidationmissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Utilitedemission", DbType="VarChar(20)")]
		public string Utilitedemission
		{
			get
			{
				return this._Utilitedemission;
			}
			set
			{
				if ((this._Utilitedemission != value))
				{
					this.OnUtilitedemissionChanging(value);
					this.SendPropertyChanging();
					this._Utilitedemission = value;
					this.SendPropertyChanged("Utilitedemission");
					this.OnUtilitedemissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idappelant", DbType="Int")]
		public System.Nullable<int> Idappelant
		{
			get
			{
				return this._Idappelant;
			}
			set
			{
				if ((this._Idappelant != value))
				{
					if (this._Appelant_table1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdappelantChanging(value);
					this.SendPropertyChanging();
					this._Idappelant = value;
					this.SendPropertyChanged("Idappelant");
					this.OnIdappelantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arriveappel", DbType="VarChar(30)")]
		public string arriveappel
		{
			get
			{
				return this._arriveappel;
			}
			set
			{
				if ((this._arriveappel != value))
				{
					this.OnarriveappelChanging(value);
					this.SendPropertyChanging();
					this._arriveappel = value;
					this.SendPropertyChanged("arriveappel");
					this.OnarriveappelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destinationdesire", DbType="VarChar(30)")]
		public string destinationdesire
		{
			get
			{
				return this._destinationdesire;
			}
			set
			{
				if ((this._destinationdesire != value))
				{
					this.OndestinationdesireChanging(value);
					this.SendPropertyChanging();
					this._destinationdesire = value;
					this.SendPropertyChanged("destinationdesire");
					this.OndestinationdesireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="VarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Appeltable_Horraire_de_la_mission", Storage="_Horraire_de_la_mission", ThisKey="CleAppel", OtherKey="cleappel")]
		public EntitySet<Horraire_de_la_mission> Horraire_de_la_mission
		{
			get
			{
				return this._Horraire_de_la_mission;
			}
			set
			{
				this._Horraire_de_la_mission.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Appeltable_Appelant_table", Storage="_Appelant_table", ThisKey="CleAppel", OtherKey="cleappel")]
		public EntitySet<Appelant_table> Appelant_table
		{
			get
			{
				return this._Appelant_table;
			}
			set
			{
				this._Appelant_table.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Appelant_table_Appeltable", Storage="_Appelant_table1", ThisKey="Idappelant", OtherKey="ID_appelant", IsForeignKey=true)]
		public Appelant_table Appelant_table1
		{
			get
			{
				return this._Appelant_table1.Entity;
			}
			set
			{
				Appelant_table previousValue = this._Appelant_table1.Entity;
				if (((previousValue != value) 
							|| (this._Appelant_table1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Appelant_table1.Entity = null;
						previousValue.Appeltable1.Remove(this);
					}
					this._Appelant_table1.Entity = value;
					if ((value != null))
					{
						value.Appeltable1.Add(this);
						this._Idappelant = value.ID_appelant;
					}
					else
					{
						this._Idappelant = default(Nullable<int>);
					}
					this.SendPropertyChanged("Appelant_table1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Horraire_de_la_mission(Horraire_de_la_mission entity)
		{
			this.SendPropertyChanging();
			entity.Appeltable = this;
		}
		
		private void detach_Horraire_de_la_mission(Horraire_de_la_mission entity)
		{
			this.SendPropertyChanging();
			entity.Appeltable = null;
		}
		
		private void attach_Appelant_table(Appelant_table entity)
		{
			this.SendPropertyChanging();
			entity.Appeltable = this;
		}
		
		private void detach_Appelant_table(Appelant_table entity)
		{
			this.SendPropertyChanging();
			entity.Appeltable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ficheparmotifcreate")]
	public partial class ficheparmotifcreate
	{
		
		private System.Nullable<int> _cle;
		
		private string _motif;
		
		public ficheparmotifcreate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cle", DbType="Int")]
		public System.Nullable<int> cle
		{
			get
			{
				return this._cle;
			}
			set
			{
				if ((this._cle != value))
				{
					this._cle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motif", DbType="VarChar(20)")]
		public string motif
		{
			get
			{
				return this._motif;
			}
			set
			{
				if ((this._motif != value))
				{
					this._motif = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fichesparappel")]
	public partial class fichesparappel
	{
		
		private System.Nullable<int> _cle;
		
		private string _arriveappel;
		
		public fichesparappel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cle", DbType="Int")]
		public System.Nullable<int> cle
		{
			get
			{
				return this._cle;
			}
			set
			{
				if ((this._cle != value))
				{
					this._cle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arriveappel", DbType="VarChar(30)")]
		public string arriveappel
		{
			get
			{
				return this._arriveappel;
			}
			set
			{
				if ((this._arriveappel != value))
				{
					this._arriveappel = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fichesparmedreg")]
	public partial class fichesparmedreg
	{
		
		private System.Nullable<int> _cle;
		
		private string _medreg;
		
		public fichesparmedreg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cle", DbType="Int")]
		public System.Nullable<int> cle
		{
			get
			{
				return this._cle;
			}
			set
			{
				if ((this._cle != value))
				{
					this._cle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medreg", DbType="VarChar(20)")]
		public string medreg
		{
			get
			{
				return this._medreg;
			}
			set
			{
				if ((this._medreg != value))
				{
					this._medreg = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fichesparparam")]
	public partial class fichesparparam
	{
		
		private System.Nullable<int> _cle;
		
		private string _param;
		
		public fichesparparam()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cle", DbType="Int")]
		public System.Nullable<int> cle
		{
			get
			{
				return this._cle;
			}
			set
			{
				if ((this._cle != value))
				{
					this._cle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param", DbType="VarChar(20)")]
		public string param
		{
			get
			{
				return this._param;
			}
			set
			{
				if ((this._param != value))
				{
					this._param = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.registertbl")]
	public partial class registertbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nom;
		
		private string _prenom;
		
		private string _telephone;
		
		private string _identifiant;
		
		private string _motdepasse;
		
		private string _role;
		
		private System.Nullable<int> _pk1;
		
		private string _service;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OntelephoneChanging(string value);
    partial void OntelephoneChanged();
    partial void OnidentifiantChanging(string value);
    partial void OnidentifiantChanged();
    partial void OnmotdepasseChanging(string value);
    partial void OnmotdepasseChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void Onpk1Changing(System.Nullable<int> value);
    partial void Onpk1Changed();
    partial void OnserviceChanging(string value);
    partial void OnserviceChanged();
    #endregion
		
		public registertbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="NVarChar(50)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="NVarChar(50)")]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this.OntelephoneChanging(value);
					this.SendPropertyChanging();
					this._telephone = value;
					this.SendPropertyChanged("telephone");
					this.OntelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifiant", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string identifiant
		{
			get
			{
				return this._identifiant;
			}
			set
			{
				if ((this._identifiant != value))
				{
					this.OnidentifiantChanging(value);
					this.SendPropertyChanging();
					this._identifiant = value;
					this.SendPropertyChanged("identifiant");
					this.OnidentifiantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motdepasse", DbType="NVarChar(50)")]
		public string motdepasse
		{
			get
			{
				return this._motdepasse;
			}
			set
			{
				if ((this._motdepasse != value))
				{
					this.OnmotdepasseChanging(value);
					this.SendPropertyChanging();
					this._motdepasse = value;
					this.SendPropertyChanged("motdepasse");
					this.OnmotdepasseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NVarChar(50)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk1", DbType="Int")]
		public System.Nullable<int> pk1
		{
			get
			{
				return this._pk1;
			}
			set
			{
				if ((this._pk1 != value))
				{
					this.Onpk1Changing(value);
					this.SendPropertyChanging();
					this._pk1 = value;
					this.SendPropertyChanged("pk1");
					this.Onpk1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service", DbType="VarChar(10)")]
		public string service
		{
			get
			{
				return this._service;
			}
			set
			{
				if ((this._service != value))
				{
					this.OnserviceChanging(value);
					this.SendPropertyChanging();
					this._service = value;
					this.SendPropertyChanged("service");
					this.OnserviceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
